# splunk_inputs.conf
# Configuration for Splunk Universal Forwarder inputs on Windows host.

[default]
host = WIN10-WORKSTATION

[WinEventLog://Security]
index    = win_security
disabled = 0

[WinEventLog://Application]
index    = win_security
disabled = 0
